In [1]:
import timeit

import numpy as np
import torch

In [2]:
torch.cuda.is_available()

True

In [3]:
torch.manual_seed(seed=25)

size = 3

a_cpu = torch.rand((size, size))
b_cpu = torch.rand((size, size))

a_gpu = torch.rand((size, size)).to('cuda')
b_gpu = torch.rand((size, size)).to('cuda')

a_cpu, b_cpu, a_gpu, b_gpu

(tensor([[0.7518, 0.1929, 0.0629],
         [0.9118, 0.3828, 0.2990],
         [0.5933, 0.2911, 0.2416]]),
 tensor([[0.5582, 0.0481, 0.3497],
         [0.3520, 0.9528, 0.0284],
         [0.8488, 0.3947, 0.5181]]),
 tensor([[0.9726, 0.8813, 0.0056],
         [0.3056, 0.9384, 0.7949],
         [0.4399, 0.1766, 0.8739]], device='cuda:0'),
 tensor([[0.1425, 0.4682, 0.6254],
         [0.3040, 0.7923, 0.4691],
         [0.6875, 0.9917, 0.2772]], device='cuda:0'))

In [18]:
sizes = np.logspace(start=1, stop=3, base=10, num=10, dtype='int')
sizes

array([  10,   16,   27,   46,   77,  129,  215,  359,  599, 1000])

In [19]:
for size in sizes:
    print(size)
    cpu_time = timeit.timeit(
        stmt='a_cpu @ b_cpu',
        setup=f'import torch; size={size}; torch.manual_seed(seed=25);'
               'a_cpu = torch.rand((size, size));'
               'b_cpu = torch.rand((size, size))',
        number=1000
    )
    print(f'CPU: {cpu_time}')
    gpu_time = timeit.timeit(
        stmt='a_gpu @ b_gpu',
        setup=f'import torch; size={size}; torch.manual_seed(seed=25);'
               'a_gpu = torch.rand((size, size)).to("cuda");'
               'b_gpu = torch.rand((size, size)).to("cuda")',
        number=1000
    )
    print(f'GPU: {gpu_time}')
    print()

10
CPU: 0.004221938999762642
GPU: 0.010856169999897247

16
CPU: 0.004214320999381016
GPU: 0.010659270999894943

27
CPU: 0.00461152400021092
GPU: 0.01113562600039586

46
CPU: 0.005908520000048156
GPU: 0.011284045000138576

77
CPU: 0.009652632999859634
GPU: 0.01167060300031153

129
CPU: 0.019891240000106336
GPU: 0.01097854300041945

215
CPU: 0.06608145800055354
GPU: 0.011664187999485875

359
CPU: 0.23586963399975502
GPU: 0.011807068000052823

599
CPU: 1.0229465570000684
GPU: 0.04277707900018868

1000
CPU: 4.174758564999138
GPU: 0.24110733900033665

